/* Tests de Mickaël, joués dans la bulle d'outils (onglet Tests, revue guidée).
   Depuis le 2026-10-09 : Claude vérifie d'abord sur le vrai site avec son robot (outils/robot/) le fonctionnement, les parcours,
   les saisies, les calculs et ce qui se mesure. Ici, seulement ce que Mickaël seul peut juger : graphisme à l'œil, sa tablette,
   clarté des textes, prise en main. 5 à 10 points par écran.
   Un groupe = { g: titre, p: [état, écran] préparé avant son 1er test, l: tests }.
   Un test = [identifiant stable, ce qu'il faut faire, ce qu'on doit constater, préparation propre (facultative, sinon null),
   numéro de la version qui l'a modifié, pourquoi]. Règle : chaque modification de la maquette met à jour ces deux derniers champs
   des tests touchés ; la bulle les propose alors dans « Corrections à vérifier ».
   États : 'out' déconnecté, 'attente' compte créé mais pas confirmé, 'demo' compte d'essai (':f1' choisit le profil actif),
   'vide' nouveau compte sans profil. Les identifiants ne changent jamais : les résultats y sont rattachés.
   Anciens tests (147, jusqu'au 2026-10-09) et leurs résultats : outils/archive/. */
window.RC_TESTS=[
 {g:'Se connecter',p:['out','#connexion'],l:[
  ['cx1','Regarde l’écran « Se connecter » dans son ensemble.','Il te plaît : logo, titre, champs et boutons sont bien alignés, rien ne paraît serré, vide ou de travers.',null,27,'plus de défilement inutile ; « Pas encore de compte ? » retiré (tes notes 1 et 2)'],
  ['cx2','Lis tous les textes, y compris les petits : « E-mail », « Mot de passe », « Mot de passe oublié ? » et la ligne verte du bas.','Tu les lis sans effort sur ta tablette. (Sur téléphone, ces petits textes font 11 px, comme dans la maquette validée : dis-moi s’ils te paraissent trop petits.)'],
  ['cx3','Touche le champ E-mail.','Le clavier s’ouvre sans cacher le champ. En faisant défiler, tu atteins le bouton « Se connecter » sans fermer le clavier.'],
  ['cx4','Tourne la tablette (portrait puis paysage), puis remets-la.','L’écran se remet en place à chaque fois, rien n’est coupé ni décalé.'],
  ['cx5','Touche l’œil à droite du champ Mot de passe, deux fois.','L’œil est facile à toucher du doigt et tu comprends ce qu’il fait (montrer puis cacher le mot de passe).'],
  ['cx6','Écris gouverneur@exemple.fr, un mauvais mot de passe, puis touche « Se connecter ».','Le message « E-mail ou mot de passe incorrect. » se voit bien et se comprend. (Texte proposé par Claude : dis-moi s’il te va.)'],
  ['cx7','Connecte-toi maintenant avec gouverneur@exemple.fr et le mot de passe rok12345, sans aide.','Tu as trouvé tout de suite où écrire et quoi toucher, et tu arrives sur l’Accueil.']]},
 {g:'Créer un compte',p:['out','#connexion'],l:[
  ['in1','Touche « Créer un compte » en bas, puis « Se connecter » pour revenir, deux ou trois fois.','La carte garde la même taille d’un écran à l’autre, et aucun des deux écrans ne défile.',null,27,'les 5 écrans de compte ont la même taille de carte (ta note 3)'],
  ['in2','Sur « Créer un compte », remplis les 3 champs à la suite avec le clavier de la tablette.','Le clavier ne cache jamais le champ où tu écris ; la touche « Suivant » du clavier, si elle existe, passe au champ suivant.',['out','#inscription']],
  ['in3','Trompe-toi exprès : adresse « mickael@exemple », mot de passe « abc », confirmation « abd », puis « Créer mon compte ».','Les messages rouges sous les champs se voient bien et tu sais tout de suite quoi corriger.',['out','#inscription']],
  ['in4','Lis les messages : « Saisis une adresse valide, par exemple nom@exemple.fr. », « Au moins 8 caractères. », « Les mots de passe ne correspondent pas. »','Ils sont clairs et sur le bon ton. (Les deux premiers sont proposés par Claude.)'],
  ['in5','Remplace l’adresse par gouverneur@exemple.fr, mets deux mots de passe identiques de 8 caractères, puis « Créer mon compte ».','Le message « Un compte existe déjà avec cette adresse… » est clair et te dit quoi faire.']]},
 {g:'Confirmer l’e-mail',p:['attente','#confirmation'],l:[
  ['cf1','Regarde et lis l’écran « Confirme ton e-mail ».','Tu comprends qu’il faut ouvrir l’e-mail reçu. La phrase est maintenant « Un e-mail de confirmation t’a été envoyé. ».',null,27,'phrase « Un e-mail de confirmation t’a été envoyé. » (ta note 4)'],
  ['cf2','Touche « Renvoyer l’e-mail ».','Le message « E-mail renvoyé. » se voit bien.'],
  ['cf3','Touche « ✉ Simuler le lien de l’e-mail » dans le bandeau des tests (c’est comme toucher le lien reçu par e-mail).','Tu arrives sur l’Accueil d’un compte neuf, avec le message « E-mail confirmé. Bienvenue ! ». L’arrivée te paraît claire et le bouton « Créer mon premier profil » saute aux yeux.']]},
 {g:'Mot de passe oublié',p:['out','#connexion'],l:[
  ['mo1','Touche « Mot de passe oublié ? » sous le champ E-mail.','Le lien est facile à toucher du doigt. Le titre de cet écran est plus petit que « Se connecter », comme dans la maquette validée : dis-moi si ça te gêne.'],
  ['mo2','Écris personne@exemple.fr, puis « Envoyer le lien ».','Le message « Aucun compte avec cette adresse. Vérifie-la, ou crée un compte. » est clair.',['out','#mot-de-passe-oublie']],
  ['mo3','Écris gouverneur@exemple.fr, puis « Envoyer le lien ».','Le message « E-mail envoyé à gouverneur@exemple.fr : touche le lien qu’il contient… » est clair.'],
  ['mo4','Touche « ✉ Simuler le lien de l’e-mail » dans le bandeau, choisis un nouveau mot de passe (deux fois le même, 8 caractères ou plus), puis « Enregistrer ».','Tu es connecté et le message « Nouveau mot de passe enregistré. » reste affiché assez longtemps pour être lu.']]},
 {g:'Déconnexion et appli installée',p:['demo','#plus'],l:[
  ['dx1','Dans Plus, touche « Se déconnecter », puis confirme.','Tu reviens sur « Se connecter » avec « Tu es déconnecté. Tes profils restent enregistrés. » : c’est clair.'],
  ['dx2','Supprime l’icône de la maquette déjà installée (appui long › Désinstaller), puis réinstalle-la depuis Chrome (menu ⋮ › Installer l’application) et ouvre-la depuis la nouvelle icône.','L’icône est l’anneau doré avec RC au milieu, son nom est « RoK Maquette », et elle s’ouvre sans barre du navigateur.',null,28,'icône RC (anneau doré) au lieu de la couronne (ta note 5) et nom « RoK Maquette » ; réinstalle la maquette pour les voir']]},
 {g:'Accueil · vue d’ensemble',p:['demo','#accueil'],l:[
  ['ac1','Regarde l’Accueil sur ta tablette, en portrait.','La nouvelle organisation te convient : le profil sur toute la largeur, à gauche ce qu’il faut faire (alertes, priorités, routine), à droite où tu en es (en cours, événements, objectif, aperçu, semaine). Tout se lit bien, rien n’est serré.'],
  ['ac2','Tourne la tablette en paysage, puis remets-la en portrait.','L’Accueil reste lisible dans les deux sens et se remet en place.'],
  ['ac3','Passe d’un profil à l’autre avec les onglets en haut (Principal, Ferme 1, Ferme 2).','Tout suit le profil choisi, y compris « En cours », « À surveiller » et « Ma semaine ».',null,34,'les deux colonnes commencent à la même hauteur (ta note 7)'],
  ['ac12','Crée un profil sur ce compte neuf (« Créer mon premier profil »), puis regarde l’Accueil.','Une seule carte « Renseigne ta ville » en haut à gauche, avec le nombre de valeurs et, à droite, « Tout renseigner », qui ouvre la saisie rapide de Ma ville. Les valeurs à renseigner ne sont pas répétées dans les priorités ni dans « À surveiller ».',['vide','#accueil'],34,'bouton « Tout renseigner » à droite de la carte (ta note 8)']]},
 {g:'Accueil · priorités et routine',p:['demo','#accueil'],l:[
  ['ac4','Change le temps de jeu (10 min, 30 min, 1 h) au-dessus des priorités.','La liste s’adapte au temps choisi et tu comprends pourquoi certaines actions apparaissent ou disparaissent.',null,34,'ligne « N actions · ≈ X min sur Y » retirée (ta note 6)'],
  ['ac5','Dans « Routine du jour », coche deux tâches.','Les cases sont faciles à toucher, les tâches cochées laissent la place aux suivantes et le compteur avance.',null,34,'la tâche cochée s’efface en fondu (ta note 9)'],
  ['ac6','Touche « Tout voir », puis « Modifier la liste » : renomme une ligne, retires-en une, ajoutes-en une, puis « Enregistrer ».','La modification est facile et la liste change bien sur l’Accueil.',null,34,'heure en UTC (minuit), phrases retirées (tes notes 10 et 11)']]},
 {g:'Accueil · en cours et alertes',p:['demo','#accueil'],l:[
  ['ac7','Dans « En cours », touche « + Ajouter » et ajoute une recherche avec un temps restant écrit comme dans le jeu (par exemple 1j 4h 30m).','C’est facile à saisir et l’heure de fin affichée est juste.'],
  ['ac8','Lis « À surveiller ».','Chaque alerte est claire et tu sais quoi faire : ressources exposées au pillage, bâtisseur libre, marche incomplète, inventaire ancien.'],
  ['ac9','Touche « 1 bâtisseur libre ».','La fenêtre d’ajout s’ouvre, déjà réglée sur « Construction ».']]},
 {g:'Accueil · événements',p:['demo','#accueil'],l:[
  ['ac10','Regarde « Prochains événements », puis touche « Calendrier ».','Les dates et les heures (heure de France) sont claires, et un événement en cours se repère tout de suite.'],
  ['ac11','Dans le calendrier, touche « Ajouter » et ajoute un événement avec une date dans quelques jours.','C’est facile ; il apparaît à sa place dans le calendrier et sur l’Accueil.']]},
 {g:'Ma ville · bâtiments',p:['demo','#ma-ville-progression'],l:[
  ['vp1','Regarde Ma ville › Bâtiments sur ta tablette, en portrait, puis en paysage (et sur un téléphone si tu peux).','Même modèle que Ressources : 4 tuiles (Économique, Militaire, Autres, Saison de KvK) qui disent combien de bâtiments sont au niveau de ton Hôtel de ville, puis le détail, une case par bâtiment et par exemplaire (4 fermes, 4 moulins…). C’est clair et beau.',null,72,'Bâtiments comme Ressources'],
  ['vp7','Ouvre la fiche de ton profil (Accueil, touche ton profil), regarde « Réglages », puis touche « Niveau VIP » et reviens.','Niveau VIP, bâtisseurs, bonus de vitesse et civilisation sont dans ton profil ; la fenêtre du niveau VIP ramène au profil.',null,71,'réglages dans le profil'],
  ['vp8','Dans Ma ville, ouvre l’onglet « Recherches et troupes ». Touche une case de troupes (par exemple Archers, niveau 5), écris un nombre et « Enregistrer ».','Même modèle que Ressources : 4 tuiles (Infanterie, Cavalerie, Archers, Siège : total et part du niveau 5), puis une case par niveau ; la case et la tuile changent. Les noms des types et des niveaux sont-ils ceux du jeu ? Recherches : encore des exemples.',null,73,'troupes comme Ressources'],
  ['vp2','Dans le détail, touche la case « Taverne », change son niveau et « Enregistrer ». Puis touche le nom « Fermes » à gauche de sa ligne.','La case s’ouvre seule et change ; « Fermes » ouvre la page des fermes avec l’historique (ta correction de la Taverne y est gardée de la même façon). Le Mur, entouré d’or, dit « niv. 24 requis ».',null,72,'une case se remplit seule'],
  ['vp3','Regarde les bâtiments : Économique, Militaire, Autres.','Il ne manque aucun bâtiment à niveau de ton jeu, ils sont rangés comme dans le jeu et portent les noms du jeu (Réserve, Moulin à bois, Comptoir…). Sinon, laisse une note.'],
  ['vp6','Regarde le dernier groupe, « Saison de KvK ».','Forum d’état, Mine de cristal et Centre de recherche de cristal y sont ; tu comprends que les deux bâtiments de cristal disparaissent à la fin de la saison.'],
  ['vp5','Touche la tuile « Fermes », puis « Corriger » : change le niveau d’une ferme et enregistre.','Une case par ferme, c’est clair ; la tuile affiche ensuite le bon niveau.'],
  ['vp4','Regarde le badge en haut, à côté de « Importer ».','Il dit « Exemples, non enregistrés » et c’est clair. Dans ta version réelle, il dira « Enregistré », ou « En attente d’envoi » si l’enregistrement n’a pas pu partir.']]},
 {g:'Ma ville · inventaire',p:['demo','#ma-ville-inventaire'],l:[
  ['vi1','Regarde les onglets de l’inventaire : Ressources, Accélérateurs, Boosts, Équipement, Attirail, Autre.','Ce sont les onglets de l’Inventaire du jeu, dans le même ordre.'],
  ['vi2','Touche la tuile « Nourriture ». Change « En ville » (par exemple 40,5 M) et le nombre d’une caisse, puis « Enregistrer ».','La fenêtre est facile à remplir, les tailles de caisses sont celles du jeu ; la tuile, le résumé en haut (au total, en ville, en caisses) et la partie Nourriture du détail des caisses changent.',null,59,'onglet Ressources refait (ton choix n° 2)'],
  ['vi3','Dans Accélérateurs, regarde les tuiles, puis touche la tuile « Généraux » (ou le nom « Généraux » dans le détail).','Les tuiles n’ont plus la petite ligne « N accélérateurs » (ta note 12). Les durées sont celles du jeu ; celles marquées d’un * (24 h et plus) ne sont pas encore vérifiées : dis-moi si tu en as dans ton inventaire.',null,60,'petites lignes retirées (ta note 12)'],
  ['vi5','Regarde l’onglet Ressources de l’inventaire, sur ta tablette puis sur un téléphone si tu peux.','Les 4 tuiles (en caisses en bleu plein) avec ce qui peut être pillé, Gemmes · Coffres · Packs centrés, puis le détail des caisses : toutes les tailles, même à 0, une ligne par ressource avec une case par taille. Il prend beaucoup moins de place qu’avant. C’est beau ; sinon, dis ce qui te gêne.',null,61,'détail des caisses compact, toutes les tailles'],
  ['vi6','Dans le panneau Gemmes · Coffres · Packs, touche « Coffres », puis « Packs ».','Chacun ouvre sa propre fenêtre, avec le contenu de chaque niveau comme dans le jeu. Remplis tes quantités, enregistre : le panneau et le détail des caisses se mettent à jour.',null,59,'Coffres et Packs dans le nouveau panneau'],
  ['vi10','Dans Ressources, touche une case du détail (par exemple Nourriture, 10 000), écris un nombre, puis « Enregistrer ». Fais pareil sur une case de Gemmes, de Coffres ou de Packs.','Une petite fenêtre s’ouvre pour cette case seulement, avec le clavier des chiffres ; la case, la tuile et les totaux changent. Laisse le champ vide pour effacer la case.',null,62,'remplir une case seule (ta note 6)'],
  ['vi11','Regarde l’onglet Ressources sur ta tablette, puis sur un téléphone si tu peux (ta version réelle aussi).','Plus de titre « Ressources », de ligne d’import, de ligne « Détail des caisses » ni de crayon ; le texte des cases et celui des bulles de pillage sont centrés ; aucun nombre ne passe à la ligne, même « × 42 410 » dans tes packs.',null,62,'tes notes 1 à 5 et les nombres coupés'],
  ['vi12','Ouvre l’onglet Accélérateurs (tablette, puis téléphone si tu peux). Touche une case du détail, par exemple Construction, 15 min, écris un nombre et « Enregistrer ».','Même modèle que Ressources : les tuiles, puis une ligne par type avec une case par durée, même à 0, alignées d’une ligne à l’autre ; les durées des généraux (24 h à 30 j) dessous. La case et la tuile Construction changent.',null,63,'Accélérateurs comme Ressources'],
  ['vi13','Regarde le haut de Ma ville et des 6 onglets de l’inventaire, puis la ligne « Coffres « Choisissez un » » du détail des Ressources.','Plus de « Profil Principal » ni de titre en haut des onglets ; « Coffres « Choisissez un » » tient sur une ligne.',null,63,'tes notes 7 et 8, titres retirés'],
  ['vi14','Ouvre l’onglet Boosts (tablette, puis téléphone si tu peux). Touche une case du détail, par exemple Défense, 24 h, écris un nombre et « Enregistrer ».','Même modèle que Ressources et Accélérateurs : 3 tuiles simples, puis une ligne par famille avec une case par objet, même à 0 ; les réserves affichent leur effet (« Réserve +20 000 »). La case et la tuile Défense changent.',null,65,'Boosts comme Ressources'],
  ['vi15','Ouvre l’onglet Équipement (tablette, puis téléphone si tu peux). Touche une case du détail, par exemple Cuir, Épique, écris un nombre et « Enregistrer ».','Même modèle que les autres onglets : 8 tuiles simples, puis une ligne par famille avec une case par qualité, même à 0 ; « Coffres à ouvrir » en 3 lignes. La case et la tuile Cuir changent.',null,66,'Équipement comme Ressources'],
  ['vi16','Ouvre l’onglet Attirail. Touche la case « Épique » de la ligne Pièces d’attirail, écris le nom d’une pièce et « Ajouter ».','Même modèle que les autres onglets : 2 tuiles simples, puis le détail. La fenêtre « Ajouter une pièce d’attirail » s’ouvre avec « Épique » déjà choisi ; la pièce apparaît dans ta liste et la case Épique compte une pièce de plus.',null,67,'Attirail comme Ressources'],
  ['vi17','Ouvre l’onglet Autre. Touche une case du détail, par exemple Lumière d’étoile · bénies, Légendaire, écris un nombre et « Enregistrer ».','Même modèle que les autres onglets : 9 tuiles, puis le détail en 11 lignes (la lumière d’étoile en 3 : simples, bénies, lots). Tomes et points d’action montrent ce que vaut chaque case. La tuile Points d’action garde « Avec tes potions ».',null,68,'Autre comme Ressources'],
  ['vi18','Dans Autre, regarde la tuile Migration, puis touche « Ajouter un objet » et écris « Passeports ».','La tuile Migration affiche 12 ; « Autres objets » est vide. L’ajout de « Passeports » est refusé avec « Cet objet a déjà sa case : Autre › Migration › Passeport ».',null,69,'passeports à leur place (ta remarque)'],
  ['vi7','Dans Accélérateurs, regarde la tuile « Généraux », puis le détail par durée en bas.','La tuile donne « Avec les généraux » pour chaque type (construction : 82 j 10 h chez toi). En bas, la carte Généraux prend toute la largeur, sans case vide. C’est clair et beau.',null,51,'carte Généraux sur toute la largeur (ta proposition 1)'],
  ['vi8','Regarde les 6 onglets de l’inventaire l’un après l’autre, puis touche une tuile de chaque.','Les 6 onglets ont le même modèle : des tuiles (grand nombre et à quoi servent les objets), puis le détail avec une case par objet ou par qualité. Chaque tuile ouvre la fenêtre de sa famille. C’est clair et beau.',null,68,'les 6 onglets sur le même modèle'],
  ['vi9','Dans « Autre », regarde la tuile « Points d’action » (en bas, sur toute la largeur). Touche-la : sous tes potions, règle le niveau des barbares que tu attaques et le talent « −10 points ».','C’est ta proposition 1 : à droite, « Avec tes potions » donne les barbares, l’EXP par commandant et les jours de recharge ; plus de carte en bas. La fenêtre explique le calcul. Dis-moi si les coûts (50 points, puis 40 en enchaînant) sont ceux de ton jeu.',null,58,'rendu pro : 3 chiffres clés avec une phrase chacun'],
  ['vi4','Dans « Autre », touche « Ajouter un objet », ajoute un objet de ton inventaire avec sa quantité, puis touche-le pour le modifier et le supprimer.','C’est simple et clair.']]},
 {g:'Importer · lecture par Claude',p:['demo','#import'],l:[
  ['im3','Ouvre Importer et regarde l’écran, sans rien toucher.','C’est la piste A que tu as choisie : un grand bouton « Choisir mes captures », les 3 étapes en images, et c’est beau. Sinon, dis ce qui te gêne.',null,43,'piste A, ton choix'],
  ['im1','Choisis toutes tes captures entières de l’Inventaire (onglets Ressources et Accélérateurs, en faisant défiler jusqu’en bas), puis touche « Lire ».','Tu vois la lecture avancer, avec l’onglet de chaque capture, puis la relecture. Aucune case n’est dite « coupée » si toutes tes captures se suivent.',null,43,'piste A ; fausse alerte « cases coupées » corrigée'],
  ['im2','Vérifie les lignes « À vérifier » (choisis le type si on te le demande), touche « Confirmer les éléments sûrs », puis « Enregistrer ».','Les nombres de tes captures arrivent dans Ma ville › Inventaire du profil Principal, comme dans le jeu ; rien d’autre n’a changé.'],
  ['im5','Importe tes captures des onglets Boosts, Équipement, Attirail et Autre (chaque onglet défilé jusqu’en bas), puis « Lire » et « Enregistrer ».','Les tuiles des 4 onglets se remplissent avec tes vrais nombres (plans 250, sculptures, tomes…) ; les objets pas reconnus sont signalés.',null,53,'nouveau : lecture des 4 autres onglets'],
  ['im4','Refais un import avec ta capture du haut de l’onglet Ressources (coffres et packs).','Les coffres « Choisissez un » et les packs sont lus avec leur niveau. S’il y a un doute (deux packs gris), on te demande A, B ou C ; au prochain import, tes niveaux sont repris sans question.',null,48,'nouveau : lecture des coffres et packs']]}
];
